### ISSUE TITLE
Tworzenie formularza edycji wydarzenia

### ISSUE THREAD

**Issue by laboratoriumkodu** [jakub-c/videopoint-react-pierwsze-kroki#1]
W kursie brak momentu tworzenia CSS dla formularza edycji wydarzenia. W przypadku osób z małym doświadczeniem będzie to miejsce gdzie zatrzymają się one na dłużej.

**Comment by jakub-c** [comment]
@laboratoriumkodu tak jak w poprzednim wątku, dziękuję Ci za cenny głos - i za to, że zwracasz uwagę na proces tworzenia pełnego CSS'a w kursie. Masz rację, jeśli ktoś nie miał z CSS'em nigdy do czynienia zatrzyma się w tym miejscu na dłużej. Z drugiej strony z tego powodu umieściłem cały kod tutaj. Jeszcze raz dzięki za feedback!
