### ISSUE TITLE
Rozdziały 8.3 i 8.4

### ISSUE THREAD

**Issue by laboratoriumkodu** [jakub-c/videopoint-react-pierwsze-kroki#2]
Rozdziały 8.3 i 8.4 rozpoczynają się od tego samego miejsca a wiodą do różnych rozwiązań. Rozwiązanie z rozdziału 8.3 jest dziwne błędne i w zasadzie w kontekście tego kursu nie wiadomo po co jest rozdział 8.3

**Comment by jakub-c** [comment]
@laboratoriumkodu dziekuję Ci bardzo za zainteresowanie kursem i to, że dzielisz się pomysłami na jego ulepszenie, bardzo się z tego cieszę! Myślisz, że lepiej by było pominąć rozdział 8.3?

**Comment by laboratoriumkodu** [comment]
Myślę, że tak było by lepiej.
Pozdrawiam

Niedz., 2 cze 2019, 22:30 użytkownik Jakub <notifications@github.com>
napisał:

**Comment by jakub-c** [comment]
Dziękuję za feedback, dzięki Twojemu głosowi mój następny kurs będzie lepszy.
