### ISSUE TITLE
lekcja 6.2.2.  - https://cmder.net/  

### ISSUE THREAD

**Issue by Mat321123** [jakub-c/videopoint-react-pierwsze-kroki#3]
https://cmder.net/    - zmieniła się zawartość strony

Pozdrawiam :)

**Comment by jakub-c** [comment]
cześć @Mat321123,
dziękuję za czujność i twój feedback. Dzięki niemu kurs staje się lepszy. W dużym skrócie od czasu wydania kursu polecanym narzędziem stał się nowy Microsoft Terminal:

* ten commit uaktualnia `README` https://github.com/jakub-c/videopoint-react-pierwsze-kroki/commit/783d0d16dc8ede65591ac8e78ef9cab59cf19fc8
* nowa dokumentacja w czytelnej formie: https://github.com/jakub-c/videopoint-react-pierwsze-kroki/blob/master/README.md
